### ISSUE TITLE
Transformation ABAPGIT_ST_REPO_INFO_EXT_REQ not available

### ISSUE THREAD

**Issue by schallera** [abapGit/ADT_Backend#30]
Within eclipse extension abapGit Repositores an error message is thrown because transformation ABAPGIT_ST_REPO_INFO_EXT_REQ is not available. 

In class ZCL_ABAPGIT_RES_REPO_INFO_EXT the constants for the transformations has to be prefixed with Z:

CONSTANTS co_st_name_request          TYPE string VALUE '**Z**ABAPGIT_ST_REPO_INFO_EXT_REQ'.
CONSTANTS co_st_name_response         TYPE string VALUE '**Z**ABAPGIT_ST_REPO_INFO_EXT_RES'.

**Comment by larshp** [comment]
thanks, will you help opening a pull request for the change?

https://github.com/abapGit/ADT_Backend/blob/ced8bd330b637fdaf5ea73b5a383f2b6e2974986/src/zcl_abapgit_res_repo_info_ext.clas.abap#L26

**Comment by larshp** [comment]
@schallera try again, latest version
