### ISSUE TITLE
Push support

### ISSUE THREAD

**Issue by marcellourbani** [abapGit/ADT_Backend#44]
I got it working adapting the code from SAP.
Is it ok to publish and create a PR?

**Comment by larshp** [comment]
"adapting" ?

**Comment by marcellourbani** [comment]
Renamed cl_* to zcl_*, removed references to logging and scheduling classes,...
The whole thing was done like that, but if sap does it is fine, I don't have any right on that code. 
I wouldn't mind coding my own, but to make it compatible I would end up with very similar code anyway, expecially for the transformations

**Comment by larshp** [comment]
@absap

**Comment by absap** [comment]
@marcellourbani please feel free to create a PR.
I'll add you as a collaborator on this project.

**Comment by marcellourbani** [comment]
@absap 
What I mean is that I adapted the code from cloud platform: same logic and structure, added a z to abapgit objects, adapted the sap branded abapgit to mainstream one.

The rest of this code looks like it originated the same way, but  but I wouldn't post code originated from SAP on a public repository without permission. I didn't even push it on my own repo until I got this answer, and will remove it immediately if there was a misunderstanding

**Comment by absap** [comment]
Frankly speaking, I would have done it the same way.

I'll be working on a solution that would hopefully suit everyone. 
Until it's available, it's fine for me to continue this way

**Comment by larshp** [comment]
cool

@marcellourbani in https://github.com/abapGit/ADT_Backend/tree/lint#requirements it mentions specific version, is this still true? or does it now work with latest?

**Comment by marcellourbani** [comment]
Not sure, tried a pull on my 750 and failed, although I didn't touch that code (yet)
Will have a look later
