### ISSUE TITLE
'Fetching content' has encountered a problem

### ISSUE THREAD

**Issue by dassharma** [abapGit/ADT_Backend#51]
Hello Community,

There is a problem with the ABAPGIT ADT plugin.

Scenario: Push code to GitHub. (Stage & Commit)

While selecting the repository using the Switch Repository option and selecting the repository, the following error comes up.

'Fetching Content' has encountered a problem.

On viewing more details.
An internal error occurred during: "Fetching content".
Parameter "uri" must not be null

**Comment by absap** [comment]
Thanks for raising this issue.
Please feel free to provide a fix via PR.

**Comment by dassharma** [comment]
The NW release that we are on is 7.56 SP 0.

**Comment by larshp** [comment]
first make sure that ZABAPGIT works without ADT

**Comment by dassharma** [comment]
I checked with ZABAPGIT and it works perfectly fine. I was able to map a GitHub repository to an ABAP package.

**Comment by absap** [comment]
After the first analysis, it looks like the repository was not entirely pulled in the system (or accurately it won't update the pulled versions with the latest ones)
Also, abapGit 1.96 is installed onto the system, which is not a verified version now.

**Comment by dassharma** [comment]
The issue is resolved now.
Did a reset local on the ADT_BACKEND from ZABAPGIT. Navigate to the package in ZABAPGIT. Select advanced option from the menu which show Pull | Stage | Diff | Branch | Tag | Advanceed | Refresh. In the menu under advanced --> Reset Local. 

Once this was done, the plugin started to work as expected.
