### ISSUE TITLE
type zif_abapgit_persistence is missing from the master branch

### ISSUE THREAD

**Issue by nmalenovic** [abapGit/ADT_Backend#58]
Just pulled from master, class ZCL_ABAPGIT_RES_REPOS reports on line 26 that INCLUDE TYPE zif_abapgit_persistence=>ty_value is unknown. Looks like the custom interface is nowhere to be found.

**Comment by larshp** [comment]
pull the full abapgit version, https://docs.abapgit.org/guide-upgrade.html

**Comment by nmalenovic** [comment]
nailed it. thank you!
