### ISSUE TITLE
Archive this repo?

### ISSUE THREAD

**Issue by mbtools** [abapGit/ADT_Backend#77]
[Project Odense](https://github.com/SAP-archive/project-odense) is now officially archived. 

We might as well archive this repo

**Comment by larshp** [comment]
yea, well, probably leave it open for some time

its not possible to create issues in an archived repo, which sometimes is annoying

**Comment by MBartsch71** [comment]
The question is what means this for the developers, which are still using the ADT Backend functionality. Whate are the alternatives?

**Comment by mbtools** [comment]
Do you mean solutions built on top of these z-rest-services unrelated to ADT? Or using it with ADT on top of an on-prem system?

Anyway, this repo is already labelled as deprecated. We can just leave it as is.

**Comment by MBartsch71** [comment]
Yeah, I mean I am using abapGit on an on-prem system. Even if it is not longer supported it still works ok. And I am happy with the workflow of abapGit in Eclipse.

I mean I am also open to other suggestions ;-)

**Comment by mbtools** [comment]
Let's just keep it going until it breaks and then 🤷
